# Generated by Django 4.2.6 on 2023-10-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(default=None, max_length=100)),
                ("photo", models.ImageField(default=None, upload_to="")),
                ("iban", models.CharField(default=None, max_length=14)),
            ],
        ),
    ]
