# Generated by Django 4.2.6 on 2023-10-16 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Bank", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="account",
            table="accounts",
        ),
    ]
