# Generated by Django 4.2.6 on 2023-10-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Bank", "0002_alter_account_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="iban",
        ),
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="Iban",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default=None, max_length=3)),
                ("iban", models.CharField(default=None, max_length=14)),
                (
                    "username",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Bank.account",
                    ),
                ),
            ],
            options={
                "db_table": "iban",
            },
        ),
    ]
