# Generated by Django 4.2.6 on 2023-10-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bank", "0006_remove_account_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="balance",
            field=models.FloatField(default=0.0),
        ),
    ]
