# Generated by Django 4.2.6 on 2023-10-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bank", "0008_remove_balance_id_balance_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="currency",
            field=models.CharField(default=None, max_length=3),
        ),
    ]
