# Generated by Django 4.2.6 on 2023-10-25 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Bank", "0009_account_currency"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="balance",
            table="Balances",
        ),
    ]
