# Generated by Django 4.2.6 on 2023-10-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bank", "0010_alter_balance_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="username",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
