# Generated by Django 4.2.6 on 2023-10-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Bank", "0011_alter_balance_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="iban",
            field=models.CharField(
                default=None, max_length=14, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="balance",
            name="username",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Bank.account",
            ),
        ),
    ]
