# Generated by Django 4.2.6 on 2023-10-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bank", "0012_alter_balance_iban_alter_balance_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default=None, max_length=100)),
                ("email", models.EmailField(default=None, max_length=254)),
                ("subject", models.CharField(default=None, max_length=150)),
                ("the_request", models.TextField(default=None, max_length=1000)),
            ],
            options={
                "db_table": "Feedback",
            },
        ),
    ]
