# Generated by Django 4.2.6 on 2023-11-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bank", "0014_actionsregister"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actionsregister",
            name="iban",
        ),
        migrations.AddField(
            model_name="actionsregister",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
