# Generated by Django 4.2.6 on 2023-11-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Bank", "0015_remove_actionsregister_iban_actionsregister_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionsregister",
            name="id",
            field=models.IntegerField(
                auto_created=True, default=0, primary_key=True, serialize=False
            ),
        ),
    ]
